"""update user model and security

Revision ID: 5055cb0b9ec9
Revises: 9065147c12df
Create Date: 2026-06-06 23:30:17.890644

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5055cb0b9ec9"
down_revision: str | Sequence[str] | None = "9065147c12df"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("full_name", sa.String(length=255), nullable=True))
    op.add_column("user", sa.Column("is_active", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "is_active")
    op.drop_column("user", "full_name")
    # ### end Alembic commands ###
