"""use userrole enum for user role

Revision ID: a0ea389122bb
Revises: 5055cb0b9ec9
Create Date: 2026-06-06 23:48:25.102938

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a0ea389122bb"
down_revision: str | Sequence[str] | None = "5055cb0b9ec9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    user_role = sa.Enum("ADMIN", "MANAGER", "USER", name="userrole")
    user_role.create(op.get_bind())

    op.alter_column(
        "user",
        "role",
        existing_type=sa.VARCHAR(length=50),
        type_=user_role,
        existing_nullable=False,
        postgresql_using="role::userrole",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user",
        "role",
        existing_type=sa.Enum("ADMIN", "MANAGER", "USER", name="userrole"),
        type_=sa.VARCHAR(length=50),
        existing_nullable=False,
    )

    sa.Enum(name="userrole").drop(op.get_bind())
    # ### end Alembic commands ###
