"""add_fts_to_chunks

Revision ID: ad0f720e0e93
Revises: f24d8bb003dd
Create Date: 2026-06-07 22:16:44.373074

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "ad0f720e0e93"
down_revision: str | Sequence[str] | None = "f24d8bb003dd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "document_chunk", sa.Column("tsv_content", postgresql.TSVECTOR(), nullable=True)
    )
    op.create_index(
        "ix_document_chunk_tsv",
        "document_chunk",
        ["tsv_content"],
        unique=False,
        postgresql_using="gin",
    )
    # ### end Alembic commands ###

    # Custom trigger for FTS
    op.execute("""
        CREATE FUNCTION document_chunk_tsv_update_trigger() RETURNS trigger AS $$
        begin
          new.tsv_content := to_tsvector('english', coalesce(new.content, ''));
          return new;
        end
        $$ LANGUAGE plpgsql;
    """)
    op.execute("""
        CREATE TRIGGER tsvectorupdate BEFORE INSERT OR UPDATE
        ON document_chunk FOR EACH ROW
        EXECUTE FUNCTION document_chunk_tsv_update_trigger();
    """)

    # Update existing rows
    op.execute(
        "UPDATE document_chunk SET tsv_content = to_tsvector('english', coalesce(content, ''));"  # noqa: E501
    )


def downgrade() -> None:
    """Downgrade schema."""
    # Custom trigger removal
    op.execute("DROP TRIGGER IF EXISTS tsvectorupdate ON document_chunk;")
    op.execute("DROP FUNCTION IF EXISTS document_chunk_tsv_update_trigger();")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_document_chunk_tsv", table_name="document_chunk", postgresql_using="gin"
    )
    op.drop_column("document_chunk", "tsv_content")
    # ### end Alembic commands ###
