"""add_feedback_to_message

Revision ID: e23c156077fd
Revises: 47b472459286
Create Date: 2026-06-08 18:23:21.242227

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e23c156077fd"
down_revision: str | Sequence[str] | None = "47b472459286"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("message", sa.Column("is_useful", sa.Boolean(), nullable=True))
    op.add_column("message", sa.Column("feedback_comment", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("message", "feedback_comment")
    op.drop_column("message", "is_useful")
    # ### end Alembic commands ###
