"""add_metadata_gin_index

Revision ID: f24d8bb003dd
Revises: 2aaf018d5d81
Create Date: 2026-06-07 22:14:29.153321

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f24d8bb003dd"
down_revision: str | Sequence[str] | None = "2aaf018d5d81"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_document_chunk_metadata",
        "document_chunk",
        ["metadata"],
        unique=False,
        postgresql_using="gin",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_document_chunk_metadata",
        table_name="document_chunk",
        postgresql_using="gin",
    )
    # ### end Alembic commands ###
